<a href="https://colab.research.google.com/github/smpark0520/ESAA/blob/main/grouping_occupation_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [11]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [13]:
pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 3. Assign it to a variable called users.

In [15]:
users = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
users.head(5)

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [23]:
df = pd.DataFrame(users)
mean_age_per_occupation = df.groupby("occupation")["age"].mean()
mean_age_per_occupation

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [25]:
# 각 직업별 남성 비율(Male ratio)을 계산하고, 이를 내림차순으로 정렬하는 문
occupation_counts = df.groupby('occupation')['gender'].count() # 직업별 총 인원 수
male_counts = df[df['gender'] == 'M'].groupby('occupation')['gender'].count() # 직업별 남성 인원 수
male_ratio = male_counts / occupation_counts # 직업별 남성 비율
male_ratio.sort_values(ascending=False) # 직업별 남성 비율을 내림차순으로 정렬

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: gender, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [27]:
age_stats_per_occupation = df.groupby('occupation')['age'].agg(['min', 'max'])
age_stats_per_occupation

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [28]:
#각 직업(occupation)과 성별(gender) 조합에 대해 평균 나이(age)를 계산
mean_age = df.groupby(['occupation', 'gender'])['age'].mean().reset_index()
mean_age

       occupation gender        age
0   administrator      F  40.638889
1   administrator      M  37.162791
2          artist      F  30.307692
3          artist      M  32.333333
4          doctor      M  43.571429
5        educator      F  39.115385
6        educator      M  43.101449
7        engineer      F  29.500000
8        engineer      M  36.600000
9   entertainment      F  31.000000
10  entertainment      M  29.000000
11      executive      F  44.000000
12      executive      M  38.172414
13     healthcare      F  39.818182
14     healthcare      M  45.400000
15      homemaker      F  34.166667
16      homemaker      M  23.000000
17         lawyer      F  39.500000
18         lawyer      M  36.200000
19      librarian      F  40.000000
20      librarian      M  40.000000
21      marketing      F  37.200000
22      marketing      M  37.875000
23           none      F  36.500000
24           none      M  18.600000
25          other      F  35.472222
26          other      M  34.028986
27     programmer      F  32.166667
28     programmer      M  33.216667
29        retired      F  70.000000
30        retired      M  62.538462
31       salesman      F  27.000000
32       salesman      M  38.555556
33      scientist      F  28.333333
34      scientist      M  36.321429
35        student      F  20.750000
36        student      M  22.669118
37     technician      F  38.000000
38     technician      M  32.961538
39         writer      F  37.631579
40         writer      M  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [29]:
gender_counts = df.groupby(['occupation', 'gender']).size().unstack(fill_value=0)
total_counts = gender_counts.sum(axis=1)
gender_percentages = gender_counts.div(total_counts, axis=0) * 100
gender_percentages

gender                 F           M
occupation
administrator  45.569620   54.430380
artist         46.428571   53.571429
doctor          0.000000  100.000000
educator       27.368421   72.631579
engineer        2.985075   97.014925
entertainment  11.111111   88.888889
executive       9.375000   90.625000
healthcare     68.750000   31.250000
homemaker      85.714286   14.285714
lawyer         16.666667   83.333333
librarian      56.862745   43.137255
marketing      38.461538   61.538462
none           44.444444   55.555556
other          34.285714   65.714286
programmer      9.090909   90.909091
retired         7.142857   92.857143
salesman       25.000000   75.000000
scientist       9.677419   90.322581
student        30.612245   69.387755
technician      3.703704   96.296296
writer         42.222222   57.777778